Repository AI-Play/User-Auth, pull requests merged in 2022-03, with the labels that each got.

#11 [FeatureMade] 회원가입 & login & 닉네임 변경 & 회원 탈퇴
  base/settings.py
  base/urls.py
  userauth/admin.py
  userauth/migrations/0001_initial.py
  userauth/models.py
  userauth/urls.py
  userauth/views.py
Labels: 분류: 기능 구현

#14 [FeatureMade] 비밀번호 찾기 & 프로필 사진 변경
  base/settings.py
  userauth/models.py
  userauth/urls.py
  userauth/views.py
Labels: 분류: 기능 구현

#20 [FeatureMade] 사용자 관련 기능 업데이트 (프로필 사진 변경 기능 제외)
  README.md
  base/settings.py
  requirements.txt
  userauth/migrations/0001_initial.py
  userauth/models.py
  userauth/urls.py
  userauth/views.py
Labels: 분류: 기능 구현, 분류: 문서화

#23 User-Auth initial deployment setting
  .gitignore
  Procfile
  base/settings.py
  requirements.txt
  userauth/migrations/0002_alter_func_log_is_worked.py
  userauth/models.py
  userauth/views.py
Labels: 분류: 기능 구현

#25 [FeatureMade] JWT setting created
  base/settings.py
  userauth/urls.py
  userauth/views.py
Labels: 분류: 기능 구현

#26 [FeatureMade] CORS Origins updated
  base/settings.py
  userauth/migrations/0001_initial.py
  userauth/migrations/0002_alter_func_log_is_worked.py
  userauth/models.py
  userauth/views.py
Labels: 분류: 기능 구현

#29 [DOCU] README & requirements updated, settings DEBUG changed
  README.md
  base/settings.py
  requirements.txt
Labels: 분류: 문서화

#31 [BUG] remove_jwt - samesite, secure attrs added
  Dockerfile
  base/settings.py
  userauth/views.py
Labels: 분류: 버그
